
--
-- MANUAL SECTORS PER DATASET
-- see also sector.csv in draft for exported sectors
--

ALTER SEQUENCE sector_key_seq RESTART WITH 20000;

-- Cycads
INSERT INTO sector (dataset_key, mode, subject_rank, subject_name, target_rank, target_name, created_by, modified_by)
VALUES
(1163, 0,   'class'::rank, 'Cycadopsida',   'phylum'::rank, 'Tracheophyta',  0,0);

--
-- Staphbase
--
INSERT INTO sector (dataset_key, mode, subject_rank, subject_name, target_rank, target_name, created_by, modified_by)
VALUES
(1204, 0,   'family'::rank, 'Synteliidae',           'superfamily'::rank, 'Histeroidea',  0,0),
(1204, 0,   'superfamily'::rank, 'Hydrophiloidea',   'order'::rank, 'Coleoptera',  0,0),
(1204, 0,   'superfamily'::rank, 'Staphylinoidea',   'order'::rank, 'Coleoptera',  0,0);

--
-- World Plants
--
INSERT INTO sector (dataset_key, mode, subject_rank, subject_name, target_rank, target_name, created_by, modified_by)
VALUES
-- Liliopsida
(1141, 0,   'family'::rank, 'Juncaceae',          'order'::rank, 'Poales',  0,0),
-- Magnoliopsida merges
(1141, 1,   'family'::rank, 'Pteridophyllaceae',  'family'::rank, 'Papaveraceae',  0,0),
(1141, 1,   'family'::rank, 'Parnassiaceae',  'family'::rank, 'Celastraceae',  0,0),
(1141, 1,   'family'::rank, 'Hypseocharitaceae',  'family'::rank, 'Geraniaceae',  0,0),
(1141, 1,   'family'::rank, 'Ledocarpaceae',  'family'::rank, 'Vivianiaceae',  0,0),
(1141, 1,   'family'::rank, 'Comandraceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Thesiaceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Cervantesiaceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Nanodeaceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Viscaceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Rehmanniaceae',  'family'::rank, 'Orobanchaceae',  0,0),
(1141, 1,   'family'::rank, 'Pteleocarpaceae',  'family'::rank, 'Gelsemiaceae',  0,0),
(1141, 1,   'family'::rank, 'Morinaceae',  'family'::rank, 'Caprifoliaceae',  0,0),
(1141, 1,   'family'::rank, 'Ixerbaceae',  'family'::rank, 'Strasburgeriaceae',  0,0),
(1141, 1,   'family'::rank, 'Valerianaceae',  'family'::rank, 'Caprifoliaceae',  0,0),
(1141, 1,   'family'::rank, 'Amphorogynaceae',  'family'::rank, 'Santalaceae',  0,0),
(1141, 1,   'family'::rank, 'Cochlospermaceae',  'family'::rank, 'Bixaceae',  0,0),
(1141, 1,   'family'::rank, 'Peltantheraceae',  'family'::rank, 'Bignoniaceae',  0,0),
-- Batidaceae needs manual creation in CoL tree
(1141, 1,   'family'::rank, 'Bataceae',  'family'::rank, 'Batidaceae',  0,0),
-- Magnoliopsida attachments
(1141, 0,   'family'::rank, 'Amborellaceae',   'order'::rank, 'Amborellales',  0,0),
(1141, 0,   'family'::rank, 'Griseliniaceae',   'order'::rank, 'Apiales',  0,0),
(1141, 0,   'family'::rank, 'Pennantiaceae',   'order'::rank, 'Apiales',  0,0),
(1141, 0,   'family'::rank, 'Torricelliaceae',   'order'::rank, 'Apiales',  0,0),
(1141, 0,   'family'::rank, 'Phyllonomaceae',   'order'::rank, 'Aquifoliales',  0,0),
(1141, 0,   'family'::rank, 'Alseuosmiaceae',   'order'::rank, 'Asterales',  0,0),
(1141, 0,   'family'::rank, 'Argophyllaceae',   'order'::rank, 'Asterales',  0,0),
(1141, 0,   'family'::rank, 'Pentaphragmataceae',   'order'::rank, 'Asterales',  0,0),
(1141, 0,   'family'::rank, 'Phellinaceae',   'order'::rank, 'Asterales',  0,0),
(1141, 0,   'family'::rank, 'Austrobaileyaceae',   'order'::rank, 'Austrobaileyales',  0,0),
(1141, 0,   'family'::rank, 'Trimeniaceae',   'order'::rank, 'Austrobaileyales',  0,0),
(1141, 0,   'family'::rank, 'Aextoxicaceae',   'order'::rank, 'Berberidopsidales',  0,0),
(1141, 0,   'family'::rank, 'Berberidopsidaceae',   'order'::rank, 'Berberidopsidales',  0,0),
(1141, 0,   'family'::rank, 'Akaniaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Batidaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Bretschneideraceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Capparaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Caricaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Cleomaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Emblingiaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Gyrostemonaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Moringaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Pentadiplandraceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Resedaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Salvadoraceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Stixaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Tropaeolaceae',   'order'::rank, 'Brassicales',  0,0),
(1141, 0,   'family'::rank, 'Bruniaceae',   'order'::rank, 'Bruniales',  0,0),
(1141, 0,   'family'::rank, 'Buxaceae',   'order'::rank, 'Buxales',  0,0),
(1141, 0,   'family'::rank, 'Didymelaceae',   'order'::rank, 'Buxales',  0,0),
(1141, 0,   'family'::rank, 'Ancistrocladaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Asteropeiaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Barbeuiaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Basellaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Didiereaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Dioncophyllaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Drosophyllaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Frankeniaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Gisekiaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Lophiocarpaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Molluginaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Nyctaginaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Physenaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Phytolaccaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Plumbaginaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Polygonaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Rhabdodendraceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Sarcobataceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Stegnospermataceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Tamaricaceae',   'order'::rank, 'Caryophyllales',  0,0),
(1141, 0,   'family'::rank, 'Celastraceae',   'order'::rank, 'Celastrales',  0,0),
(1141, 0,   'family'::rank, 'Lepidobotryaceae',   'order'::rank, 'Celastrales',  0,0),
(1141, 0,   'family'::rank, 'Ceratophyllaceae',   'order'::rank, 'Ceratophyllales',  0,0),
(1141, 0,   'family'::rank, 'Grubbiaceae',   'order'::rank, 'Cornales',  0,0),
(1141, 0,   'family'::rank, 'Hydrostachyaceae',   'order'::rank, 'Cornales',  0,0),
(1141, 0,   'family'::rank, 'Aphloiaceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Geissolomataceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Guamatelaceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Staphyleaceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Stachyuraceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Strasburgeriaceae',   'order'::rank, 'Crossosomatales',  0,0),
(1141, 0,   'family'::rank, 'Apodanthaceae',   'order'::rank, 'Cucurbitales',  0,0),
(1141, 0,   'family'::rank, 'Coriariaceae',   'order'::rank, 'Cucurbitales',  0,0),
(1141, 0,   'family'::rank, 'Corynocarpaceae',   'order'::rank, 'Cucurbitales',  0,0),
(1141, 0,   'family'::rank, 'Cucurbitaceae',   'order'::rank, 'Cucurbitales',  0,0),
(1141, 0,   'family'::rank, 'Dilleniaceae',   'order'::rank, 'Dilleniales',  0,0),
(1141, 0,   'family'::rank, 'Roridulaceae',   'order'::rank, 'Ericales',  0,0),
(1141, 0,   'family'::rank, 'Tetrameristaceae',   'order'::rank, 'Ericales',  0,0),
(1141, 0,   'family'::rank, 'Polygalaceae',   'order'::rank, 'Fabales',  0,0),
(1141, 0,   'family'::rank, 'Quillajaceae',   'order'::rank, 'Fabales',  0,0),
(1141, 0,   'family'::rank, 'Surianaceae',   'order'::rank, 'Fabales',  0,0),
(1141, 0,   'family'::rank, 'Juglandaceae',   'order'::rank, 'Fagales',  0,0),
(1141, 0,   'family'::rank, 'Myricaceae',   'order'::rank, 'Fagales',  0,0),
(1141, 0,   'family'::rank, 'Metteniusaceae',   'order'::rank, 'Garryales',  0,0),
(1141, 0,   'family'::rank, 'Geraniaceae',   'order'::rank, 'Geraniales',  0,0),
(1141, 0,   'family'::rank, 'Melianthaceae',   'order'::rank, 'Geraniales',  0,0),
(1141, 0,   'family'::rank, 'Gunneraceae',   'order'::rank, 'Gunnerales',  0,0),
(1141, 0,   'family'::rank, 'Myrothamnaceae',   'order'::rank, 'Gunnerales',  0,0),
(1141, 0,   'family'::rank, 'Dipentodontaceae',   'order'::rank, 'Huerteales',  0,0),
(1141, 0,   'family'::rank, 'Tapisciaceae',   'order'::rank, 'Huerteales',  0,0),
(1141, 0,   'family'::rank, 'Carlemanniaceae',   'order'::rank, 'Lamiales',  0,0),
(1141, 0,   'family'::rank, 'Mazaceae',   'order'::rank, 'Lamiales',  0,0),
(1141, 0,   'family'::rank, 'Peltantheraceae',   'order'::rank, 'Lamiales',  0,0),
(1141, 0,   'family'::rank, 'Thomandersiaceae',   'order'::rank, 'Lamiales',  0,0),
(1141, 0,   'family'::rank, 'Atherospermataceae',   'order'::rank, 'Laurales',  0,0),
(1141, 0,   'family'::rank, 'Siparunaceae',   'order'::rank, 'Laurales',  0,0),
(1141, 0,   'family'::rank, 'Degeneriaceae',   'order'::rank, 'Magnoliales',  0,0),
(1141, 0,   'family'::rank, 'Eupomatiaceae',   'order'::rank, 'Magnoliales',  0,0),
(1141, 0,   'family'::rank, 'Himantandraceae',   'order'::rank, 'Magnoliales',  0,0),
(1141, 0,   'family'::rank, 'Achariaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Balanopaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Bonnetiaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Calophyllaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Clusiaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Ctenolophonaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Dichapetalaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Elatinaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Erythroxylaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Euphroniaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Goupiaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Humiriaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Hypericaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Ixonanthaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Linaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Malpighiaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Ochnaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Passifloraceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Podostemaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Rafflesiaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Rhizophoraceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Salicaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Trigoniaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Violaceae',   'order'::rank, 'Malpighiales',  0,0),
(1141, 0,   'family'::rank, 'Metteniusaceae',   'order'::rank, 'Metteniusales',  0,0),
(1141, 0,   'family'::rank, 'Combretaceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Crypteroniaceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Lythraceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Onagraceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Penaeaceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Vochysiaceae',   'order'::rank, 'Myrtales',  0,0),
(1141, 0,   'family'::rank, 'Hydatellaceae',   'order'::rank, 'Nymphaeales',  0,0),
(1141, 0,   'family'::rank, 'Brunelliaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Cephalotaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Connaraceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Cunoniaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Elaeocarpaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Huaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Oxalidaceae',   'order'::rank, 'Oxalidales',  0,0),
(1141, 0,   'family'::rank, 'Picramniaceae',   'order'::rank, 'Picramniales',  0,0),
(1141, 0,   'family'::rank, 'Hydnoraceae',   'order'::rank, 'Piperales',  0,0),
(1141, 0,   'family'::rank, 'Juncaceae',   'order'::rank, 'Poales',  0,0),
(1141, 0,   'family'::rank, 'Platanaceae',   'order'::rank, 'Proteales',  0,0),
(1141, 0,   'family'::rank, 'Proteaceae',   'order'::rank, 'Proteales',  0,0),
(1141, 0,   'family'::rank, 'Berberidaceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Circaeasteraceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Eupteleaceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Lardizabalaceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Menispermaceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Papaveraceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Ranunculaceae',   'order'::rank, 'Ranunculales',  0,0),
(1141, 0,   'family'::rank, 'Barbeyaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Cannabaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Dirachmaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Elaeagnaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Moraceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Rhamnaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Rosaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Ulmaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Urticaceae',   'order'::rank, 'Rosales',  0,0),
(1141, 0,   'family'::rank, 'Sabiaceae',   'order'::rank, 'Proteales',  0,0),
(1141, 0,   'family'::rank, 'Balanophoraceae',   'order'::rank, 'Santalales',  0,0),
(1141, 0,   'family'::rank, 'Anacardiaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Biebersteiniaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Burseraceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Kirkiaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Meliaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Nitrariaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Rutaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Sapindaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Simaroubaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Tetradiclidaceae',   'order'::rank, 'Sapindales',  0,0),
(1141, 0,   'family'::rank, 'Altingiaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Aphanopetalaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Cercidiphyllaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Crassulaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Cynomoriaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Daphniphyllaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Grossulariaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Haloragaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Hamamelidaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Iteaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Paeoniaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Peridiscaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Saxifragaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Tetracarpaeaceae',   'order'::rank, 'Saxifragales',  0,0),
(1141, 0,   'family'::rank, 'Solanaceae',   'order'::rank, 'Solanales',  0,0),
(1141, 0,   'family'::rank, 'Trochodendraceae',   'order'::rank, 'Trochodendrales',  0,0),
(1141, 0,   'family'::rank, 'Vahliaceae',   'order'::rank, 'Vahliales',  0,0),
(1141, 0,   'family'::rank, 'Vitaceae',   'order'::rank, 'Vitales',  0,0),
(1141, 0,   'family'::rank, 'Krameriaceae',   'order'::rank, 'Zygophyllales',  0,0),
(1141, 0,   'family'::rank, 'Zygophyllaceae',   'order'::rank, 'Zygophyllales',  0,0),
(1141, 0,   'family'::rank, 'Asteraceae',   'order'::rank, 'Asterales',  0,0),
(1141, 0,   'family'::rank, 'Schisandraceae',   'order'::rank, 'Austrobaileyales',  0,0),
(1141, 0,   'family'::rank, 'Casuarinaceae',   'order'::rank, 'Fagales',  0,0),
-- inside other sectors
(1141, 0,   'genus'::rank,  'Astragalus',   'family'::rank, 'Fabaceae',  0,0);

